services:
  postgres:
    image: postgres:16-alpine
    container_name: franchise-db
    environment:
      POSTGRES_DB: franchise_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "123456"
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: franchise-app
    ports:
      - "8081:8081"
    environment:
      DB_URL: postgres:5432/franchise_db
      DB_USERNAME: postgres
      DB_PASSWORD: "123456"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
